package kr.or.ddit.users;

import kr.or.ddit.users.vo.ResumeScVO;

public class ResumeRenderer implements IResumeRenderer {
	
	
	private final String PATTERN = "<div id=\"content\">\r\n"
			+ "	<div id=\"resume_print_area\" class=\"resume_print_area\">\r\n"
			+ "		<div class=\"print_wrap\">\r\n"
			+ "			<h2 class=\"blind\">이력서 VIEW</h2>\r\n"
			+ "			<section class=\"resume_basic\">\r\n"
			+ "				<div class=\"resume_view\">\r\n"
			+ "					<div class=\"resume_top\">\r\n"
			+ "						<h1 class=\"user_name\">홍길동</h1>\r\n"
			+ "						<div class=\"user_state\">신입</div>\r\n"
			+ "					</div>\r\n"
			+ "\r\n"
			+ "					<p class=\"user_desc\">여, 1996 (27세)</p>\r\n"
			+ "					<p class=\"user_privacy except-print\">비노출(마스킹) 처리된 개인정보는 기업이 이력서\r\n"
			+ "						열람/제안시 정상 노출됩니다.</p>\r\n"
			+ "					<ul class=\"user_info\">\r\n"
			+ "						<li class=\"user_email\">thd*******@naver.com</li>\r\n"
			+ "						<li class=\"user_phone\"><span>010-****-8538 </span></li>\r\n"
			+ "						<li class=\"user_number\"><span>010-****-8538</span></li>\r\n"
			+ "						<li class=\"user_address\">(34965) 대전 중구 계백로1654번길</li>\r\n"
			+ "					</ul>\r\n"
			+ "					<div class=\"picture_box\">\r\n"
			+ "						<div class=\"picture\">\r\n"
			+ "							<img alt=\"\"\r\n"
			+ "								src=\"https://www.saramin.co.kr/zf_user/persons/picture?idx=12915821|39a7bdfbec809420fa50ea2ee76cb6069e79fee3c7f0701d7797dbc7c4779b1c\"\r\n"
			+ "								border=\"0\">\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "				</div>\r\n"
			+ "\r\n"
			+ "				<ul class=\"resume_dashboard\">\r\n"
			+ "					<li class=\"item\"><strong class=\"tit\">학력</strong>\r\n"
			+ "					<p class=\"txt\">\r\n"
			+ "							대학교(4년) 졸업<br>대전대학교\r\n"
			+ "						</p></li>\r\n"
			+ "					<li class=\"item\"><strong class=\"tit\">전공</strong>\r\n"
			+ "					<p class=\"txt\">\r\n"
			+ "							경영학과<br>국제언어학과\r\n"
			+ "						</p></li>\r\n"
			+ "					<li class=\"item\"><strong class=\"tit\">업무경험</strong>\r\n"
			+ "					<p class=\"txt\">-</p></li>\r\n"
			+ "					<li class=\"item\"><strong class=\"tit\">희망연봉</strong>\r\n"
			+ "					<p class=\"txt\">2,200~2,400만원</p></li>\r\n"
			+ "					<li class=\"item\"><strong class=\"tit\">포트폴리오</strong>\r\n"
			+ "					<p class=\"txt\">-</p></li>\r\n"
			+ "				</ul>\r\n"
			+ "			</section>\r\n"
			+ "			<div class=\"resume_part\">\r\n"
			+ "				<div class=\"part\">\r\n"
			+ "					<div class=\"box_tit\">\r\n"
			+ "						<h2 class=\"tit\">학력</h2>\r\n"
			+ "						<span class=\"txt\">대학교(4년) 졸업</span>\r\n"
			+ "					</div>\r\n"
			+ "					<div class=\"box_con\">\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">\r\n"
			+ "								<span>대전대학교</span>(4년제) <span class=\"txt\">(주간)</span>\r\n"
			+ "							</h3>\r\n"
			+ "							<span class=\"date\">2015.03 ~ 2019.02 (졸업)</span>\r\n"
			+ "							<p class=\"desc\">경영학과</p>\r\n"
			+ "							<dl class=\"faculty\">\r\n"
			+ "								<dt>복수전공</dt>\r\n"
			+ "								<dd>국제언어학과</dd>\r\n"
			+ "								<dt>학점</dt>\r\n"
			+ "								<dd>3.34/4.5</dd>\r\n"
			+ "								<dt>지역</dt>\r\n"
			+ "								<dd>대전</dd>\r\n"
			+ "							</dl>\r\n"
			+ "						</div>\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">\r\n"
			+ "								<span>대전성모여자고등학교</span>\r\n"
			+ "							</h3>\r\n"
			+ "							<span class=\"date\">2012.03 ~ 2014.12 (졸업)</span>\r\n"
			+ "							<p class=\"desc\">문과계열</p>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "				</div>\r\n"
			+ "				<div class=\"part\">\r\n"
			+ "					<div class=\"box_tit\">\r\n"
			+ "						<h2 class=\"tit\">자격/어학/수상</h2>\r\n"
			+ "					</div>\r\n"
			+ "					<div class=\"box_con\">\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">\r\n"
			+ "								컴퓨터활용능력2급 <span class=\"txt\">(최종합격)</span>\r\n"
			+ "							</h3>\r\n"
			+ "							<span class=\"date\">2021.04 </span>\r\n"
			+ "							<p class=\"desc\">대한상공회의소</p>\r\n"
			+ "						</div>\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">\r\n"
			+ "								직업상담사2급 <span class=\"txt\">(최종합격)</span>\r\n"
			+ "							</h3>\r\n"
			+ "							<span class=\"date\">2021.08 </span>\r\n"
			+ "							<p class=\"desc\">한국산업인력공단</p>\r\n"
			+ "						</div>\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">\r\n"
			+ "								전산회계1급 (국가공인) <span class=\"txt\">(최종합격)</span>\r\n"
			+ "							</h3>\r\n"
			+ "							<span class=\"date\">2022.03 </span>\r\n"
			+ "							<p class=\"desc\">한국세무사협회</p>\r\n"
			+ "						</div>\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">\r\n"
			+ "								2종보통운전면허 <span class=\"txt\">(최종합격)</span>\r\n"
			+ "							</h3>\r\n"
			+ "							<span class=\"date\">2020.03 </span>\r\n"
			+ "							<p class=\"desc\">경찰청(운전면허시험관리단)</p>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "				</div>\r\n"
			+ "				<div class=\"part\">\r\n"
			+ "					<div class=\"box_tit\">\r\n"
			+ "						<h2 class=\"tit\">\r\n"
			+ "							포트폴리오 및<br>기타문서\r\n"
			+ "						</h2>\r\n"
			+ "					</div>\r\n"
			+ "					<div class=\"box_con\">\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">자격증</h3>\r\n"
			+ "							<a\r\n"
			+ "								href=\"https://pds3.saramin.co.kr/webfile/download_memberfile_security.php?appmode=slide_webview&amp;file=person%2Fresume_filebox%2F202203%2F03%2Fr84njp_9cqf-1mntupk_resume_filebox.pdf&amp;name2=%EC%A0%84%EC%82%B0%ED%9A%8C%EA%B3%84_1%EA%B8%89_%EA%B9%80%EC%86%8C%EC%9B%90_%EC%9E%90%EA%B2%A9%EC%A6%9D.pdf\"\r\n"
			+ "								title=\"전산회계 1급 김소원 자격증.pdf\" style=\"\" class=\"file_link\"><span>전산회계\r\n"
			+ "									1급 김소원 자격증.pdf</span></a>\r\n"
			+ "						</div>\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">자격증</h3>\r\n"
			+ "							<a\r\n"
			+ "								href=\"https://pds3.saramin.co.kr/webfile/download_memberfile_security.php?appmode=slide_webview&amp;file=person%2Fresume_filebox%2F202109%2F25%2Fqzz863_jcwk-1mntupk_resume_filebox.pdf&amp;name2=%EC%A7%81%EC%97%85%EC%83%81%EB%8B%B4%EC%82%AC_%EC%9E%90%EA%B2%A9%EC%A6%9D.pdf\"\r\n"
			+ "								title=\"직업상담사 자격증.pdf\" style=\"\" class=\"file_link\"><span>직업상담사\r\n"
			+ "									자격증.pdf</span></a>\r\n"
			+ "						</div>\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">자격증</h3>\r\n"
			+ "							<a\r\n"
			+ "								href=\"https://pds3.saramin.co.kr/webfile/download_memberfile_security.php?appmode=slide_webview&amp;file=person%2Fresume_filebox%2F202109%2F25%2Fqzz7wx_o574-1mntupk_resume_filebox.pdf&amp;name2=%EC%BB%B4%ED%99%9C2%EA%B8%89_%EC%9E%90%EA%B2%A9%EC%B7%A8%EB%93%9D%ED%99%95%EC%9D%B8%EC%84%9C_%EA%B9%80%EC%86%8C%EC%9B%90.pdf\"\r\n"
			+ "								title=\"컴활2급 자격취득확인서_김소원.pdf\" style=\"\" class=\"file_link\"><span>컴활2급\r\n"
			+ "									자격취득확인서_김소원.pdf</span></a>\r\n"
			+ "						</div>\r\n"
			+ "					</div>\r\n"
			+ "				</div>\r\n"
			+ "				<div class=\"part part_letter\">\r\n"
			+ "					<div class=\"box_tit\">\r\n"
			+ "						<h2 class=\"tit\">자기소개서</h2>\r\n"
			+ "					</div>\r\n"
			+ "					<div class=\"box_con\">\r\n"
			+ "						<div class=\"box_list\">\r\n"
			+ "							<h3 class=\"tit\">생활신조 및 가치관</h3>\r\n"
			+ "							<p class=\"desc\">\r\n"
			+ "								[생활신조 및 가치관]<br> <br> 내용\r\n"
			+ "							</p>\r\n"
			+ "						</div>\r\n"
			+ "					</div>";
	
	
	

	@Override
	public String renderResume(ResumeScVO resume) {
		StringBuffer html = new StringBuffer();
		
		
		return String.format(PATTERN, null);
	}
	
}
